#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
MLD_phase_hist.py

Takes global map of MLD generated by 


@author: albion lawrence
"""

import numpy as np
import matplotlib.pyplot as plt
#import scipy.stats as stats
import cartopy.crs as ccrs
from scipy.optimize import least_squares
from scipy.stats import chi2
import matplotlib.ticker as mticker

months = ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec']

mld_map = np.load('../submesoscale_seasonality_data/global_maps/mld_map_4deg.npy',encoding='latin1',allow_pickle=True)
mld_annual = np.mean(mld_map,axis=2)

sinusoid1 = np.exp(2j*np.pi*np.arange(12)/12)
sinusoid1 = sinusoid1[np.newaxis,np.newaxis,:]

mld_mode1_map = np.sum(mld_map*sinusoid1,axis=2)
mld_phase1_map = 12*np.angle(mld_mode1_map)/(2*np.pi) % 12

mld_max_south = np.array([])
mld_max_north = np.array([])

mld_phase_south = np.ndarray.flatten(mld_phase1_map[:15,:])
mld_phase_north = np.ndarray.flatten(mld_phase1_map[15:,:])

for lat_band in range(15):
    for lon_band in range(90):
        if np.isnan(mld_map[lat_band,lon_band,:]).any() == False:
            mld_max_south = np.hstack([mld_max_south,np.argmax(mld_map[lat_band,lon_band,:])])
        if np.isnan(mld_map[lat_band+15,lon_band,:]).any() == False:
            mld_max_north = np.hstack([mld_max_north,np.argmax(mld_map[lat_band+15,lon_band,:])])
            

# plt.figure(figsize = (12,8))

# plt.pcolormesh(mld_annual)

fig, ax = plt.subplots(1, 2, sharex=True, sharey=True, figsize=(8, 3))

ax[0].hist(mld_max_north,label="NH",align='left',bins=(np.arange(13)),color='tab:blue')
ax[0].hist(mld_max_south,label="SH",align='left',bins=(np.arange(13)),color='tab:orange')
ax[0].set_xticks(np.arange(12))
ax[0].set_xticklabels(['J','F','M','A','M','J','J','A','S','O','N','D'])
ax[0].set_xlim(-0.5, 11.5)
ax[0].set_title('(a)', loc="left")
ax[0].set_title('month of max MLD')
ax[0].yaxis.set_major_locator(mticker.MultipleLocator(base=100))
ax[0].legend(frameon=False, loc=2)

ax[1].hist(mld_phase_north,label="NH",align='left',bins=(np.arange(13)),color='tab:blue')
ax[1].hist(mld_phase_south,label="SH",align='left',bins=(np.arange(13)),color='tab:orange')
ax[1].set_title('(b)', loc="left")
ax[1].set_title('MLD phase')

fig.tight_layout(w_pad=2.5)
fig.savefig("fig/phase_mld.pdf")

plt.show()
